"""auth e pessoas

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-09 15:37:38.965872
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alunos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("data_nascimento", sa.Date(), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alunos")),
    )
    op.create_index(op.f("ix_alunos_nome"), "alunos", ["nome"], unique=False)
    op.create_index(
        "uq_alunos_cpf_ativo",
        "alunos",
        ["cpf"],
        unique=True,
        postgresql_where=sa.text("cpf IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "SECRETARIA",
                "FINANCEIRO",
                "PROFESSOR",
                "RESPONSAVEL",
                name="role",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "funcionarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("cargo", sa.String(length=100), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "ADMINISTRATIVO",
                "PRESTADOR_SERVICO",
                name="tipofuncionario",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_funcionarios_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_funcionarios")),
        sa.UniqueConstraint("user_id", name=op.f("uq_funcionarios_user_id")),
    )
    op.create_index(
        "uq_funcionarios_cpf_ativo",
        "funcionarios",
        ["cpf"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "professores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("formacao", sa.String(length=150), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_professores_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_professores")),
        sa.UniqueConstraint("user_id", name=op.f("uq_professores_user_id")),
    )
    op.create_index(
        "uq_professores_cpf_ativo",
        "professores",
        ["cpf"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("jti", name=op.f("uq_refresh_tokens_jti")),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "responsaveis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_responsaveis_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_responsaveis")),
        sa.UniqueConstraint("user_id", name=op.f("uq_responsaveis_user_id")),
    )
    op.create_index(op.f("ix_responsaveis_nome"), "responsaveis", ["nome"], unique=False)
    op.create_index(
        "uq_responsaveis_cpf_ativo",
        "responsaveis",
        ["cpf"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "responsavel_aluno",
        sa.Column("responsavel_id", sa.Integer(), nullable=False),
        sa.Column("aluno_id", sa.Integer(), nullable=False),
        sa.Column(
            "parentesco",
            sa.Enum(
                "MAE", "PAI", "AVO", "TIO", "OUTRO", name="parentesco", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("responsavel_financeiro", sa.Boolean(), nullable=False),
        sa.Column("pode_buscar", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["aluno_id"], ["alunos.id"], name=op.f("fk_responsavel_aluno_aluno_id_alunos")
        ),
        sa.ForeignKeyConstraint(
            ["responsavel_id"],
            ["responsaveis.id"],
            name=op.f("fk_responsavel_aluno_responsavel_id_responsaveis"),
        ),
        sa.PrimaryKeyConstraint("responsavel_id", "aluno_id", name=op.f("pk_responsavel_aluno")),
    )
    op.create_index(
        op.f("ix_responsavel_aluno_aluno_id"), "responsavel_aluno", ["aluno_id"], unique=False
    )
    op.create_index(
        "uq_responsavel_aluno_um_financeiro",
        "responsavel_aluno",
        ["aluno_id"],
        unique=True,
        postgresql_where=sa.text("responsavel_financeiro"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_responsavel_aluno_um_financeiro",
        table_name="responsavel_aluno",
        postgresql_where=sa.text("responsavel_financeiro"),
    )
    op.drop_index(op.f("ix_responsavel_aluno_aluno_id"), table_name="responsavel_aluno")
    op.drop_table("responsavel_aluno")
    op.drop_index(
        "uq_responsaveis_cpf_ativo",
        table_name="responsaveis",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_responsaveis_nome"), table_name="responsaveis")
    op.drop_table("responsaveis")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(
        "uq_professores_cpf_ativo",
        table_name="professores",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("professores")
    op.drop_index(
        "uq_funcionarios_cpf_ativo",
        table_name="funcionarios",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("funcionarios")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        "uq_alunos_cpf_ativo",
        table_name="alunos",
        postgresql_where=sa.text("cpf IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_alunos_nome"), table_name="alunos")
    op.drop_table("alunos")
    # ### end Alembic commands ###
