"""turmas e matricula

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 15:47:13.053227
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "turmas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "serie",
            sa.Enum(
                "MATERNAL_1",
                "MATERNAL_2",
                "INFANTIL_1",
                "INFANTIL_2",
                "ANO_1",
                "ANO_2",
                "ANO_3",
                "ANO_4",
                "ANO_5",
                name="serie",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("ano_letivo", sa.Integer(), nullable=False),
        sa.Column(
            "turno",
            sa.Enum("MANHA", "TARDE", "INTEGRAL", name="turno", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("capacidade", sa.Integer(), nullable=False),
        sa.Column("vagas_ocupadas", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ativa", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("capacidade BETWEEN 1 AND 30", name=op.f("ck_turmas_capacidade_maxima")),
        sa.CheckConstraint(
            "vagas_ocupadas >= 0 AND vagas_ocupadas <= capacidade",
            name=op.f("ck_turmas_vagas_ocupadas_validas"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turmas")),
        sa.UniqueConstraint(
            "serie", "ano_letivo", "turno", name=op.f("uq_turmas_serie_ano_letivo_turno")
        ),
    )
    op.create_index(op.f("ix_turmas_ano_letivo"), "turmas", ["ano_letivo"], unique=False)
    op.create_table(
        "matriculas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aluno_id", sa.Integer(), nullable=False),
        sa.Column("ano_letivo", sa.Integer(), nullable=False),
        sa.Column(
            "serie",
            sa.Enum(
                "MATERNAL_1",
                "MATERNAL_2",
                "INFANTIL_1",
                "INFANTIL_2",
                "ANO_1",
                "ANO_2",
                "ANO_3",
                "ANO_4",
                "ANO_5",
                name="serie",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "turno",
            sa.Enum("MANHA", "TARDE", "INTEGRAL", name="turno", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("turma_id", sa.Integer(), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum("NOVA", "REMATRICULA", name="tipomatricula", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PRE_MATRICULA",
                "EM_ANALISE",
                "APROVADA",
                "AGUARDANDO_PAGAMENTO",
                "ATIVA",
                "REJEITADA",
                "CANCELADA",
                name="statusmatricula",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("tamanho_farda", sa.String(length=10), nullable=True),
        sa.Column("farda_indisponivel", sa.Boolean(), nullable=False),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.Column("motivo_rejeicao", sa.Text(), nullable=True),
        sa.Column("motivo_cancelamento", sa.Text(), nullable=True),
        sa.Column("criado_por_user_id", sa.Integer(), nullable=False),
        sa.Column("decidido_por_user_id", sa.Integer(), nullable=True),
        sa.Column("decidido_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["aluno_id"], ["alunos.id"], name=op.f("fk_matriculas_aluno_id_alunos")
        ),
        sa.ForeignKeyConstraint(
            ["turma_id"], ["turmas.id"], name=op.f("fk_matriculas_turma_id_turmas")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matriculas")),
    )
    op.create_index(op.f("ix_matriculas_aluno_id"), "matriculas", ["aluno_id"], unique=False)
    op.create_index(op.f("ix_matriculas_ano_letivo"), "matriculas", ["ano_letivo"], unique=False)
    op.create_index(op.f("ix_matriculas_status"), "matriculas", ["status"], unique=False)
    op.create_index(op.f("ix_matriculas_turma_id"), "matriculas", ["turma_id"], unique=False)
    op.create_index(
        "uq_matriculas_aluno_ano_em_aberto",
        "matriculas",
        ["aluno_id", "ano_letivo"],
        unique=True,
        postgresql_where=sa.text("status NOT IN ('REJEITADA', 'CANCELADA')"),
    )
    op.create_table(
        "documentos_matricula",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("matricula_id", sa.Integer(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "CERTIDAO_NASCIMENTO",
                "CARTAO_VACINA",
                "COMPROVANTE_RESIDENCIA",
                "DOCUMENTO_RESPONSAVEL",
                name="tipodocumento",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("entregue", sa.Boolean(), nullable=False),
        sa.Column("arquivo_path", sa.String(length=255), nullable=True),
        sa.Column("arquivo_nome", sa.String(length=100), nullable=True),
        sa.Column("arquivo_content_type", sa.String(length=50), nullable=True),
        sa.Column("conferido_por_user_id", sa.Integer(), nullable=True),
        sa.Column("conferido_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["matricula_id"],
            ["matriculas.id"],
            name=op.f("fk_documentos_matricula_matricula_id_matriculas"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documentos_matricula")),
        sa.UniqueConstraint(
            "matricula_id", "tipo", name=op.f("uq_documentos_matricula_matricula_id_tipo")
        ),
    )
    op.create_index(
        op.f("ix_documentos_matricula_matricula_id"),
        "documentos_matricula",
        ["matricula_id"],
        unique=False,
    )
    op.create_table(
        "turma_professor",
        sa.Column("turma_id", sa.Integer(), nullable=False),
        sa.Column("professor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["professor_id"],
            ["professores.id"],
            name=op.f("fk_turma_professor_professor_id_professores"),
        ),
        sa.ForeignKeyConstraint(
            ["turma_id"], ["turmas.id"], name=op.f("fk_turma_professor_turma_id_turmas")
        ),
        sa.PrimaryKeyConstraint("turma_id", "professor_id", name=op.f("pk_turma_professor")),
    )
    op.create_index(
        op.f("ix_turma_professor_professor_id"), "turma_professor", ["professor_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_turma_professor_professor_id"), table_name="turma_professor")
    op.drop_table("turma_professor")
    op.drop_index(op.f("ix_documentos_matricula_matricula_id"), table_name="documentos_matricula")
    op.drop_table("documentos_matricula")
    op.drop_index(
        "uq_matriculas_aluno_ano_em_aberto",
        table_name="matriculas",
        postgresql_where=sa.text("status NOT IN ('REJEITADA', 'CANCELADA')"),
    )
    op.drop_index(op.f("ix_matriculas_turma_id"), table_name="matriculas")
    op.drop_index(op.f("ix_matriculas_status"), table_name="matriculas")
    op.drop_index(op.f("ix_matriculas_ano_letivo"), table_name="matriculas")
    op.drop_index(op.f("ix_matriculas_aluno_id"), table_name="matriculas")
    op.drop_table("matriculas")
    op.drop_index(op.f("ix_turmas_ano_letivo"), table_name="turmas")
    op.drop_table("turmas")
    # ### end Alembic commands ###
