"""assistente conversas mensagens acoes

Revision ID: 0005
Revises: fcfbc3ba5a82
Create Date: 2026-10-09 19:45:15.597726
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "fcfbc3ba5a82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistente_conversas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_assistente_conversas_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistente_conversas")),
    )
    op.create_index(
        op.f("ix_assistente_conversas_user_id"), "assistente_conversas", ["user_id"], unique=False
    )
    op.create_table(
        "assistente_acoes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversa_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ferramenta", sa.String(length=60), nullable=False),
        sa.Column(
            "argumentos",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("resumo", sa.Text(), nullable=False),
        sa.Column("destrutiva", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDENTE",
                "CONFIRMADA",
                "CANCELADA",
                "EXPIRADA",
                "FALHOU",
                name="statusacao",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column(
            "resultado",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("erro", sa.Text(), nullable=True),
        sa.Column("expira_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decidida_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversa_id"],
            ["assistente_conversas.id"],
            name=op.f("fk_assistente_acoes_conversa_id_assistente_conversas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_assistente_acoes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistente_acoes")),
    )
    op.create_index(
        op.f("ix_assistente_acoes_conversa_id"), "assistente_acoes", ["conversa_id"], unique=False
    )
    op.create_index(
        op.f("ix_assistente_acoes_status"), "assistente_acoes", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_assistente_acoes_user_id"), "assistente_acoes", ["user_id"], unique=False
    )
    op.create_table(
        "assistente_mensagens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversa_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=12), nullable=False),
        sa.Column("conteudo", sa.Text(), nullable=True),
        sa.Column(
            "tool_calls",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("tool_call_id", sa.String(length=80), nullable=True),
        sa.Column("acao_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversa_id"],
            ["assistente_conversas.id"],
            name=op.f("fk_assistente_mensagens_conversa_id_assistente_conversas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistente_mensagens")),
    )
    op.create_index(
        op.f("ix_assistente_mensagens_acao_id"), "assistente_mensagens", ["acao_id"], unique=False
    )
    op.create_index(
        op.f("ix_assistente_mensagens_conversa_id"),
        "assistente_mensagens",
        ["conversa_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assistente_mensagens_conversa_id"), table_name="assistente_mensagens")
    op.drop_index(op.f("ix_assistente_mensagens_acao_id"), table_name="assistente_mensagens")
    op.drop_table("assistente_mensagens")
    op.drop_index(op.f("ix_assistente_acoes_user_id"), table_name="assistente_acoes")
    op.drop_index(op.f("ix_assistente_acoes_status"), table_name="assistente_acoes")
    op.drop_index(op.f("ix_assistente_acoes_conversa_id"), table_name="assistente_acoes")
    op.drop_table("assistente_acoes")
    op.drop_index(op.f("ix_assistente_conversas_user_id"), table_name="assistente_conversas")
    op.drop_table("assistente_conversas")
    # ### end Alembic commands ###
