"""notas_frequencia_calendario_comunicacao_financeiro

Revision ID: 64b8896dcf65
Revises: 0003
Create Date: 2026-10-09 17:15:32.553091
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '64b8896dcf65'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabela_precos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=20), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('valor_matricula', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_mensalidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tabela_precos')),
    sa.UniqueConstraint('serie', 'ano_letivo', name=op.f('uq_tabela_precos_serie_ano_letivo'))
    )
    op.create_index(op.f('ix_tabela_precos_ano_letivo'), 'tabela_precos', ['ano_letivo'], unique=False)
    op.create_table('avisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('publico_alvo', sa.Enum('TODOS', 'TURMA', 'RESPONSAVEIS', 'PROFESSORES', name='publicoalvo', native_enum=False, length=20), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('fixado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('publicado_por_user_id', sa.Integer(), nullable=False),
    sa.Column('publicado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publicado_por_user_id'], ['users.id'], name=op.f('fk_avisos_publicado_por_user_id_users')),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_avisos_turma_id_turmas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avisos'))
    )
    op.create_table('bolsas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('percentual_desconto', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('vigencia_inicio', sa.Date(), nullable=False),
    sa.Column('vigencia_fim', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('percentual_desconto >= 0 AND percentual_desconto <= 100', name=op.f('ck_bolsas_percentual_desconto_valido')),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('fk_bolsas_aluno_id_alunos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bolsas'))
    )
    op.create_index(op.f('ix_bolsas_aluno_id'), 'bolsas', ['aluno_id'], unique=False)
    op.create_table('cobrancas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('MATRICULA', 'MENSALIDADE', 'TAXA_EXTRA', name='tipocobranca', native_enum=False, length=20), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=True),
    sa.Column('valor_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('valor_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGA', 'ATRASADA', 'CANCELADA', name='statuscobranca', native_enum=False, length=20), server_default='PENDENTE', nullable=False),
    sa.Column('pago_em', sa.DateTime(), nullable=True),
    sa.Column('gateway_referencia', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('fk_cobrancas_aluno_id_alunos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cobrancas'))
    )
    op.create_index(op.f('ix_cobrancas_aluno_id'), 'cobrancas', ['aluno_id'], unique=False)
    op.create_index(op.f('ix_cobrancas_competencia'), 'cobrancas', ['competencia'], unique=False)
    op.create_table('eventos_calendario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=2000), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('tipo', sa.Enum('PROVA', 'FERIADO', 'REUNIAO', 'EVENTO', 'OUTRO', name='tipoevento', native_enum=False, length=20), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('criado_por_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_eventos_calendario_turma_id_turmas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eventos_calendario'))
    )
    op.create_index(op.f('ix_eventos_calendario_data_inicio'), 'eventos_calendario', ['data_inicio'], unique=False)
    op.create_index(op.f('ix_eventos_calendario_turma_id'), 'eventos_calendario', ['turma_id'], unique=False)
    op.create_table('frequencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENTE', 'FALTA', 'FALTA_JUSTIFICADA', name='statusfrequencia', native_enum=False, length=20), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('lancado_por_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('fk_frequencia_aluno_id_alunos')),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_frequencia_turma_id_turmas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frequencia')),
    sa.UniqueConstraint('aluno_id', 'data', name=op.f('uq_frequencia_aluno_id_data'))
    )
    op.create_index(op.f('ix_frequencia_aluno_id'), 'frequencia', ['aluno_id'], unique=False)
    op.create_index(op.f('ix_frequencia_data'), 'frequencia', ['data'], unique=False)
    op.create_index(op.f('ix_frequencia_turma_id'), 'frequencia', ['turma_id'], unique=False)
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(length=100), nullable=False),
    sa.Column('periodo', sa.Enum('BIMESTRE_1', 'BIMESTRE_2', 'BIMESTRE_3', 'BIMESTRE_4', name='periodo', native_enum=False, length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('lancado_por_user_id', sa.Integer(), nullable=False),
    sa.Column('lancado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('fk_notas_aluno_id_alunos')),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_notas_turma_id_turmas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notas')),
    sa.UniqueConstraint('aluno_id', 'turma_id', 'disciplina', 'periodo', name=op.f('uq_notas_aluno_id_turma_id_disciplina_periodo'))
    )
    op.create_index(op.f('ix_notas_aluno_id'), 'notas', ['aluno_id'], unique=False)
    op.create_index(op.f('ix_notas_turma_id'), 'notas', ['turma_id'], unique=False)
    op.create_table('leituras_aviso',
    sa.Column('aviso_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lido_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aviso_id'], ['avisos.id'], name=op.f('fk_leituras_aviso_aviso_id_avisos')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leituras_aviso_user_id_users')),
    sa.PrimaryKeyConstraint('aviso_id', 'user_id', name=op.f('pk_leituras_aviso'))
    )
    op.create_index(op.f('ix_leituras_aviso_user_id'), 'leituras_aviso', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leituras_aviso_user_id'), table_name='leituras_aviso')
    op.drop_table('leituras_aviso')
    op.drop_index(op.f('ix_notas_turma_id'), table_name='notas')
    op.drop_index(op.f('ix_notas_aluno_id'), table_name='notas')
    op.drop_table('notas')
    op.drop_index(op.f('ix_frequencia_turma_id'), table_name='frequencia')
    op.drop_index(op.f('ix_frequencia_data'), table_name='frequencia')
    op.drop_index(op.f('ix_frequencia_aluno_id'), table_name='frequencia')
    op.drop_table('frequencia')
    op.drop_index(op.f('ix_eventos_calendario_turma_id'), table_name='eventos_calendario')
    op.drop_index(op.f('ix_eventos_calendario_data_inicio'), table_name='eventos_calendario')
    op.drop_table('eventos_calendario')
    op.drop_index(op.f('ix_cobrancas_competencia'), table_name='cobrancas')
    op.drop_index(op.f('ix_cobrancas_aluno_id'), table_name='cobrancas')
    op.drop_table('cobrancas')
    op.drop_index(op.f('ix_bolsas_aluno_id'), table_name='bolsas')
    op.drop_table('bolsas')
    op.drop_table('avisos')
    op.drop_index(op.f('ix_tabela_precos_ano_letivo'), table_name='tabela_precos')
    op.drop_table('tabela_precos')
    # ### end Alembic commands ###
