"""aluno_user_id

Revision ID: fcfbc3ba5a82
Revises: 64b8896dcf65
Create Date: 2026-10-09 17:39:04.837364
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'fcfbc3ba5a82'
down_revision: str | None = '64b8896dcf65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_alunos_user_id'), 'alunos', ['user_id'])
    op.create_foreign_key(op.f('fk_alunos_user_id_users'), 'alunos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_alunos_user_id_users'), 'alunos', type_='foreignkey')
    op.drop_constraint(op.f('uq_alunos_user_id'), 'alunos', type_='unique')
    op.drop_column('alunos', 'user_id')
    # ### end Alembic commands ###
